polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),

    path("login", views.login, name="login"),

    path('lista', views.IndexView.as_view(), name='lista'),
    path('<int:pk>/', views.DetailView.as_view(), name='detalhe'),
    path('<int:pk>/resultados/', views.ResultsViews.as_view(), name='resultados'),
    path('<int:pergunta_id>/votar/', views.votar, name='votar'),

    path("cadastro", views.cadastro, name="cadastro"),

    path("mathquest", views.mathquest, name="mathquest"),

    path("perfil", views.perfil, name="perfil"),

    path("sobre", views.sobre, name="sobre"),
     
    path("matematicaef1", views.matematicaef1, name="matematicaef1"),

    path("matematicaef2", views.matematicaef2, name="matematicaef2"),
    
    path("matematicaef3", views.matematicaef3, name="matematicaef3"),

    path("matematicaef4", views.matematicaef4, name="matematicaef4"),

    path("matematicaef5", views.matematicaef5, name="matematicaef5"),

    path("matematicaef6", views.matematicaef6, name="matematicaef6"),

    path("matematicaef7", views.matematicaef7, name="matematicaef7"),

    path("matematicaef8", views.matematicaef8, name="matematicaef8"),

    path("matematicaef9", views.matematicaef9, name="matematicaef9"),
    
    path("password_reset_form", views.password_reset_form, name="password_reset_form"),
]

tcc/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
    path("auth/", include('usuarios.urls')),

]

usuarios/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = "usuarios"
urlpatterns = [
    path('cadastro/', views.cadastro, name="cadastro"),
    path('login/', views.login_usuario, name="login"),
    path('sair/', views.sair, name="sair"),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Usuario(models.Model):
    nome = models.CharField (max_length=100)
    email = models.EmailField (max_length=100, unique=True)
    senha = models.CharField (max_length=100)
 
    def __str__ (self):
        return self.nome
        
class Pergunta (models.Model):
    texto_pergunta = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField('data de publicação')

    def __str__(self):
        return self.texto_pergunta
    
    def publicada_recente(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.data_publicacao <=now

    publicada_recente.admin_order_field = 'data_publicacao'
    publicada_recente.boolean = True
    publicada_recente.short_description = 'Publicação recente?'

class Alternativa (models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    texto_alternativa = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.texto_alternativa
    


    

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.db.models import F
from .models import Usuario
from django.views import generic
from django.utils import timezone
from django.shortcuts import get_object_or_404, render

from .models import Pergunta, Alternativa

class IndexView(generic.ListView):
    template_name = 'polls/lista.html'
    context_object_name = 'lista_ultimas_perguntas'

    def get_queryset(self):
        return Pergunta.objects.filter(
            data_publicacao__lte=timezone.now()
        ).order_by('-data_publicacao')[:5]
    
class DetailView(generic.DetailView):
    model = Pergunta
    template_name = 'polls/detalhe.html'

    def get_queryset(self):
        return Pergunta.objects.filter(data_publicacao__lte=timezone.now())
    
class ResultsViews(generic.DetailView):
    model = Pergunta
    template_name = 'polls/resultados.html'

def votar(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    try:
        alternativa_selecionada = pergunta.alternativa_set.get(pk=request.POST['alternativa'])

    except (KeyError, Alternativa.DoesNotExist):
        return render (request, 'polls/detalhe.html', {
            'pergunta': pergunta,
            'error_message': "Você não selecionou nenhuma alternativa",
        })
    else:
        alternativa_selecionada.votos += 1
        alternativa_selecionada.save()
        return HttpResponseRedirect(reverse('polls:resultados', args=(pergunta.id,)))
        


def index(request):
    latest_question_list = Usuario.objects.all()
    context = {"lastest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)

def login(request):
   return render(request, 'polls/login.html')

def cadastro(request):
    return render(request, 'polls/cadastro.html')
    
def mathquest(request):
    return render(request, 'polls/mathquest.html')

def perfil(request):
    return render(request, 'polls/perfil.html')

def sobre(request):
    return render(request, 'polls/sobre.html')


def matematicaef1(request):
    return render(request, 'polls/matematicaef1.html')

def matematicaef2(request):
    return render(request, 'polls/matematicaef2.html')

def matematicaef3(request):
    return render(request, 'polls/matematicaef3.html')

def matematicaef4(request):
    return render(request, 'polls/matematicaef4.html')

def matematicaef5(request):
    return render(request, 'polls/matematicaef5.html')

def matematicaef6(request):
    return render(request, 'polls/matematicaef6.html')

def matematicaef7(request):
    return render(request, 'polls/matematicaef7.html')

def matematicaef8(request):
    return render(request, 'polls/matematicaef8.html')

def matematicaef9(request):
    return render(request, 'polls/matematicaef9.html')

def password_reset_form(request):
    return render(request, 'polls/password_reset_form.html')

templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'polls/css/mathquest.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="shortcut icon" type="imagex/png" href="{% static 'polls/imagens/icone.png'%}">
  <title>MATHQUEST</title>
</head>

<body>
  <div class="header">
    <div class="title">
      <h1>Tópicos de estudos</h1>
    </div>
    <div class="submit-line">
      <input type="text" placeholder="Buscar..." />
      <button class="submit-lente" type="submit">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>

  <nav>
    <a href="{% url 'polls:mathquest' %}">Tópicos de estudos</a>
    <a href="#">Sobre</a>
    <a href="{% url 'polls:perfil' %}">Perfil</a>
    <a href="{% url 'polls:lista' %}">Quiz</a>
  </nav>




  {% block content %}
  {% endblock %}

  <script src="{% static 'polls/javascript/sobre.js' %}"></script>
</body>

</html>

templates/polls/matematicaef2.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'polls/css/matematicaef2.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="shortcut icon" type="imagex/png" href="{% static 'polls/imagens/icone.png'%}">
  <title>MATHQUEST</title>
</head>

<body>
  <div class="header">
    <div class="title">
      <h1>Matemática EF: 2º Ano</h1>
    </div>
    <div class="submit-line">
      <input type="text" placeholder="Buscar..." />
      <button class="submit-lente" type="submit">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>

  <nav>
    <a href="{% url 'polls:mathquest' %}">Tópicos de estudos</a>
    <a href="#">Sobre</a>
    <a href="{% url 'polls:perfil' %}">Perfil</a>
    <a href="{% url 'polls:lista' %}">Quiz</a>
  </nav>

  <div class="container">
    <div class="sidebar">
      <ul>
        <div class="conjunto">
        <li> <a href="#">Conhecendo os numeros</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
      </div>
      </ul>
    </div>



    <div class="greeting">
      <h1>Conhecendo os numeros</h1>
        <a>TALTAL TALsssssss
          dddddd
          dddddd
        </a>
        
      <h1>conteudo tal</h1>

      <h1>Conteudo t</h1>


      </div>

     

    
    </div>
 

</body>

</html>

templates/polls/matematicaef3.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'polls/css/matematicaef3.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="shortcut icon" type="imagex/png" href="{% static 'polls/imagens/icone.png'%}">
  <title>MATHQUEST</title>
</head>

<body>
  <div class="header">
    <div class="title">
      <h1>Matemática EF: 3º Ano</h1>
    </div>
    <div class="submit-line">
      <input type="text" placeholder="Buscar..." />
      <button class="submit-lente" type="submit">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>

  <nav>
    <a href="{% url 'polls:mathquest' %}">Tópicos de estudos</a>
    <a href="#">Sobre</a>
    <a href="{% url 'polls:perfil' %}">Perfil</a>
    <a href="{% url 'polls:lista' %}">Quiz</a>
  </nav>

  <div class="container">
    <div class="sidebar">
      <ul>
        <div class="conjunto">
        <li> <a href="#">Conhecendo os numeros</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
      </div>
      </ul>
    </div>



    <div class="greeting">
      <h1>Conhecendo os numeros</h1>
        <a>TALTAL TALsssssss
          dddddd
          dddddd
        </a>
        
      <h1>conteudo tal</h1>

      <h1>Conteudo t</h1>


      </div>

     

    
    </div>
 

</body>

</html>

templates/polls/matematicaef4.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'polls/css/matematicaef4.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="shortcut icon" type="imagex/png" href="{% static 'polls/imagens/icone.png'%}">
  <title>MATHQUEST</title>
</head>

<body>
  <div class="header">
    <div class="title">
      <h1>Matemática EF: 4º Ano</h1>
    </div>
    <div class="submit-line">
      <input type="text" placeholder="Buscar..." />
      <button class="submit-lente" type="submit">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>

  <nav>
    <a href="{% url 'polls:mathquest' %}">Tópicos de estudos</a>
    <a href="#">Sobre</a>
    <a href="{% url 'polls:perfil' %}">Perfil</a>
    <a href="{% url 'polls:lista' %}">Quiz</a>
  </nav>

  <div class="container">
    <div class="sidebar">
      <ul>
        <div class="conjunto">
        <li> <a href="#">Conhecendo os numeros</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
      </div>
      </ul>
    </div>



    <div class="greeting">
      <h1>Conhecendo os numeros</h1>
        <a>TALTAL TALsssssss
          dddddd
          dddddd
        </a>
        
      <h1>conteudo tal</h1>

      <h1>Conteudo t</h1>


      </div>

     

    
    </div>
 

</body>

</html>

templates/polls/matematicaef5.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'polls/css/matematicaef5.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="shortcut icon" type="imagex/png" href="{% static 'polls/imagens/icone.png'%}">
  <title>MATHQUEST</title>
</head>

<body>
  <div class="header">
    <div class="title">
      <h1>Matemática EF: 5º Ano</h1>
    </div>
    <div class="submit-line">
      <input type="text" placeholder="Buscar..." />
      <button class="submit-lente" type="submit">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>

  <nav>
    <a href="{% url 'polls:mathquest' %}">Tópicos de estudos</a>
    <a href="#">Sobre</a>
    <a href="{% url 'polls:perfil' %}">Perfil</a>
    <a href="{% url 'polls:lista' %}">Quiz</a>
  </nav>

  <div class="container">
    <div class="sidebar">
      <ul>
        <div class="conjunto">
        <li> <a href="#">Conhecendo os numeros</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
      </div>
      </ul>
    </div>



    <div class="greeting">
      <h1>Conhecendo os numeros</h1>
        <a>TALTAL TALsssssss
          dddddd
          dddddd
        </a>
        
      <h1>conteudo tal</h1>

      <h1>Conteudo t</h1>


      </div>

     

    
    </div>
 

</body>

</html>

templates/polls/matematicaef6.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'polls/css/matematicaef6.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="shortcut icon" type="imagex/png" href="{% static 'polls/imagens/icone.png'%}">
  <title>MATHQUEST</title>
</head>

<body>
  <div class="header">
    <div class="title">
      <h1>Matemática EF: 6º Ano</h1>
    </div>
    <div class="submit-line">
      <input type="text" placeholder="Buscar..." />
      <button class="submit-lente" type="submit">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>

  <nav>
    <a href="{% url 'polls:mathquest' %}">Tópicos de estudos</a>
    <a href="#">Sobre</a>
    <a href="{% url 'polls:perfil' %}">Perfil</a>
    <a href="{% url 'polls:lista' %}">Quiz</a>
  </nav>

  <div class="container">
    <div class="sidebar">
      <ul>
        <div class="conjunto">
        <li> <a href="#">Conhecendo os numeros</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
      </div>
      </ul>
    </div>



    <div class="greeting">
      <h1>Conhecendo os numeros</h1>
        <a>TALTAL TALsssssss
          dddddd
          dddddd
        </a>
        
      <h1>conteudo tal</h1>

      <h1>Conteudo t</h1>


      </div>

     

    
    </div>
 

</body>

</html>

templates/polls/matematicaef7.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'polls/css/matematicaef7.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="shortcut icon" type="imagex/png" href="{% static 'polls/imagens/icone.png'%}">
  <title>MATHQUEST</title>
</head>

<body>
  <div class="header">
    <div class="title">
      <h1>Matemática EF: 7º Ano</h1>
    </div>
    <div class="submit-line">
      <input type="text" placeholder="Buscar..." />
      <button class="submit-lente" type="submit">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>

  <nav>
    <a href="{% url 'polls:mathquest' %}">Tópicos de estudos</a>
    <a href="#">Sobre</a>
    <a href="{% url 'polls:perfil' %}">Perfil</a>
    <a href="{% url 'polls:lista' %}">Quiz</a>
  </nav>

  <div class="container">
    <div class="sidebar">
      <ul>
        <div class="conjunto">
        <li> <a href="#">Conhecendo os numeros</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
        <li> <a href="#">conteudo tal</a> </li>
      </div>
      </ul>
    </div>



    <div class="greeting">
      <h1>Conhecendo os numeros</h1>
        <a>TALTAL TALsssssss
          dddddd
          dddddd
        </a>
        
      <h1>conteudo tal</h1>

      <h1>Conteudo t</h1>


      </div>

     

    
    </div>
 

</body>

</html>

templates/polls/mathquest.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'polls/css/mathquest.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="shortcut icon" type="imagex/png" href="{% static 'polls/imagens/icone.png'%}">
  <title>MATHQUEST</title>
</head>

<body>
  <div class="header">
    <div class="title">
      <h1>Tópicos de estudos</h1>
    </div>
    <div class="submit-line">
      <input type="text" placeholder="Buscar..." />
      <button class="submit-lente" type="submit">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>

  <nav>
    <a href="{% url 'polls:mathquest' %}">Tópicos de estudos</a>
    <a href="#">Sobre</a>
    <a href="{% url 'polls:perfil' %}">Perfil</a>
    <a href="{% url 'polls:lista' %}">Quiz</a>
  </nav>


  <div class="container">
    <div class="sidebar">
      <ul>
        <div class="conjunto">
          <li> <a href="#matematica1">Matemática EF: 1º Ano</a> </li>
          <li> <a href="#matematica2">Matemática EF: 2º Ano</a> </li>
          <li> <a href="#matematica3">Matemática EF: 3º Ano</a> </li>
          <li> <a href="#matematica4">Matemática EF: 4º Ano</a> </li>
          <li> <a href="#matematica5">Matemática EF: 5º Ano</a> </li>
          <li> <a href="#matematica6">Matemática EF: 6º Ano</a> </li>
          <li> <a href="#matematica7">Matemática EF: 7º Ano</a> </li>
          <li> <a href="#matematica8">Matemática EF: 8º Ano</a> </li>
          <li> <a href="#matematica9">Matemática EF: 9º Ano</a> </li>
        </div>
      </ul>
    </div>

    <div class="product-grid">
      <div class="product-card">
        <div class="header2">
          <a href="{% url 'polls:matematicaef1' %}">Matemática EF: 1º Ano</a>
        </div>
        <div class="content">
          <div id="matematica1"class="section">
          <a href="#"> Noções de grandeza, posição e tempo </a>
          <br>
          <a href="#"> Operações </a>
          <br>
          </div>
        </div>
      </div>
      <div class="product-card">
        <div class="header2">
          Matemática EF: 2º Ano
        </div>
        <div class="content">
          <div id="matematica2"class="section">
          <a href="#"> Conhecendo os números </a>
          <br>
          <a href="#"> Operações </a>
          <br>
          </div>
        </div>
      </div>
      <div class="product-card">
        <div class="header2">
          Matemática EF: 3º Ano
        </div>
        <div class="content">
          <div id="matematica3"class="section">
          <a href="#"> Conhecendo os números </a>
          <br>
          <a href="#"> Operações </a>
          <br>
        </div>
      </div>
      </div>
      <div class="product-card">
        <div class="header2">
          Matemática EF: 4º Ano
        </div>
        <div class="content">
          <div id="matematica4"class="section">
          <a href="#"> Conhecendo os números </a>
          <br>
          <a href="#"> Operações </a>
          <br>
        </div>
      </div>
      </div>
      <div class="product-card">
        <div class="header2">
          Matemática EF: 5º Ano
        </div>
        <div class="content">
          <div id="matematica5"class="section">
          <a href="#"> Conhecendo os números </a>
          <br>
          <a href="#"> Operações </a>
          <br>
        </div>
      </div>
      </div>
      <div class="product-card">
        <div class="header2">
          Matemática EF: 6º Ano
        </div>
        <div class="content">
          <div id="matematica6"class="section">
          <a href="#"> Conhecendo os números </a>
          <br>
          <a href="#"> Operações </a>
          <br>
        </div>
      </div>
      </div>
      <div class="product-card">
        <div class="header2">
          Matemática EF: 7º Ano
        </div>
        <div class="content">
          <div id="matematica7"class="section">
          <a href="#"> Conhecendo os números </a>
          <br>
          <a href="#"> Operações </a>
          <br>
        </div>
      </div>
      </div>
      <div class="product-card">
        <div class="header2">
          Matemática EF: 8º Ano
        </div>
        <div class="content">
          <div id="matematica8"class="section">
          <a href="#"> Conhecendo os números </a>
          <br>
          <a href="#"> Operações </a>
          <br>
        </div>
      </div>
      </div>
      <div class="product-card">
        <div class="header2">
          Matemática EF: 9º Ano
        </div>
        <div class="content">
          <div id="matematica9"class="section">
          <a href="#"> Conhecendo os números </a>
          <br>
          <a href="#"> Operações </a>
          <br>
        </div>
      </div>
      </div>
    </div>
  </div>

  <script src="{% static 'polls/javascript/sobre.js' %}"></script>
</body>

</html>

templates/polls/perfil.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'polls/css/perfil.css' %}">
  <link rel="shortcut icon" type="imagex/png" href="{% static 'polls/imagens/icone.png'%}">
  <title>Perfil</title>
</head>

<body>
  <div class="header">
    <div class="title">
      <h1>Perfil</h1>
    </div>

  </div>


  <nav>
    <a href="{% url 'polls:mathquest' %}">Tópicos de estudos</a>
    <a href="#">Sobre</a>
    <a href="{% url 'polls:perfil' %}">Perfil</a>
    <a href="{% url 'polls:lista' %}">Quiz</a>
  </nav>

  <div class="container_perfil">
    <img src="{% static 'polls/imagens/perfil.png' %}" width="150" height="150" />
    <p>Bem-vindo(a): "EMAIL"</p>
    <div class="product-card-perfil">

      <a href="#">Alternar foto de perfil</a>
      
      <br>
      <br>
      <div class="icone_sair">
        <i class="bi bi-box-arrow-right"></i>
        <a href="{% url 'usuarios:sair' %}">Sair</a>
      </div>


      <div class="content">

      </div>
    </div>
  </div>
  </div>

</body>

</html>

templates/polls/sobre.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/css/sobre.css' %}">
    <title>Pop-up Exemplo</title>
    
    <a href="#openModal">Open Modal</a>

    <div id="openModal" class="modalDialog">
      <div>
        <a href="#close" title="Close" class="close">X</a>
        <h2>Popup</h2>
        <p>Isto é uma popup toda bonitinha</p>
      </div>
    </div>
</head>
<body>

</body>
</html>