polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),

    path("login", views.login, name="login"),

    path('lista', views.IndexView.as_view(), name='lista'),
    path('<int:pk>/', views.DetailView.as_view(), name='detalhe'),
    path('<int:pk>/resultados/', views.ResultsViews.as_view(), name='resultados'),
    path('<int:pergunta_id>/votar/', views.votar, name='votar'),

    path("cadastro", views.cadastro, name="cadastro"),

    path("mathquest", views.mathquest, name="mathquest"),

    path("perfil", views.perfil, name="perfil"),

    path("sobre", views.sobre, name="sobre"),
     
    path("matematicaef1", views.matematicaef1, name="matematicaef1"),

    path("matematicaef2", views.matematicaef2, name="matematicaef2"),
    
    path("matematicaef3", views.matematicaef3, name="matematicaef3"),

    path("matematicaef4", views.matematicaef4, name="matematicaef4"),

    path("matematicaef5", views.matematicaef5, name="matematicaef5"),

    path("matematicaef6", views.matematicaef6, name="matematicaef6"),

    path("matematicaef7", views.matematicaef7, name="matematicaef7"),

    path("matematicaef8", views.matematicaef8, name="matematicaef8"),

    path("matematicaef9", views.matematicaef9, name="matematicaef9"),
    
    path("password_reset_form", views.password_reset_form, name="password_reset_form"),
]

tcc/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
    path("auth/", include('usuarios.urls')),

]

usuarios/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = "usuarios"
urlpatterns = [
    path('cadastro/', views.cadastro, name="cadastro"),
    path('login/', views.login_usuario, name="login"),
    path('sair/', views.sair, name="sair"),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin 


# Create your models here.

class Usuario(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Voce não informou um email válido')
        email = self.normalize_email(email)   
        user = self.model(email=email, **extra_fields) 
        user.set_password(password)
        user.save()

        return user
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)
    
class UsuarioPersonalizado(AbstractBaseUser, PermissionsMixin):
    nome = models.CharField (max_length=100)
    email = models.EmailField (max_length=100, unique=True)
    # senha = models.CharField (max_length=100)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = Usuario()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []



    def __str__ (self):
        return self.email
    class Meta:
        verbose_name="usuario"

usuarios/forms.py
from django import forms
from .models import UsuarioPersonalizado
from django.utils.translation import gettext as _
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class UsuarioPersonalizadoCreationForm(UserCreationForm):
    
    password2 = forms.CharField(
        label="Confirme sua senha",
        strip=False,
        widget=forms.PasswordInput(
            attrs={
            'id':'password2',
            }
        )
              
    )
    class Meta:
        model = UsuarioPersonalizado
        fields = ['nome', 'email','password1', 'password2']
      
class UsuarioPersonalizadoAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(widget=forms.EmailInput)
    password = forms.CharField(label="Senha", widget=forms.PasswordInput)

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
        }

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from .forms import UsuarioPersonalizadoCreationForm, UsuarioPersonalizadoAuthenticationForm

# Create your views here.
def cadastro(request):
    form = UsuarioPersonalizadoCreationForm()
    if request.method == 'POST':
        form = UsuarioPersonalizadoCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)

            return redirect('polls:mathquest')

        print("Metodo GEt")
        
    else:
        form = UsuarioPersonalizadoCreationForm()

    return render(request, 'usuarios/cadastro.html', {'form': form})

     
def login_usuario (request):
    if request.method == 'POST':
        form = UsuarioPersonalizadoAuthenticationForm(request, request.POST)
        if form.is_valid():
            email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate (request, username=email, password=password)

            if user is not None:
                login(request, user)
                return redirect('polls:mathquest')
            
    else:
        form = UsuarioPersonalizadoAuthenticationForm()
    return render(request, 'usuarios/login.html', {'form': form})
   
def sair (request):
    logout(request)

    return redirect('usuarios:login')
       

templates/usuarios/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <title>Cadastro</title>
    <link rel="stylesheet" href="{% static 'polls/css/cadastro.css' %}">
    <link rel="shortcut icon" type="imagex/png" href="{% static 'polls/imagens/icone.png'%}">

</head>

<body>
    <div class="container">
        <div class="logo">
            <h1>Criar uma conta</h1>
        </div>

        <form action="{% url 'usuarios:cadastro' %}" method="POST"> {% csrf_token %} {{ form.as_p }}
            

            <button id = "cadastro" type="submit" href="{% url 'polls:mathquest' %}" >ENTRAR </button>
        </form>

        <div class="signup">
            <p>Já tem uma conta? <a href="{% url 'usuarios:login' %}">Entrar</a></p>
        </div>
    </div>
</body>

</html> 

templates/usuarios/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'polls/css/login.css' %}">
    <link rel="shortcut icon" type="imagex/png" href="{% static 'polls/imagens/icone.png'%}">
</head>

<body>
    <div class="container_login">
        <div class="logo">
            <h1>Criar uma conta</h1>
        </div>

        <form action="{% url 'usuarios:login' %}" method="POST"> {% csrf_token %} {{ form.as_p }}


            <button type="submit" href="{% url 'polls:mathquest' %}"> ENTRAR </button>
        </form>
        <p>
            {{custom_error}}
        </p>
        <div class="signup">
            <p>Nâo tem uma conta? <a href="{% url 'usuarios:cadastro' %}">Criar</a></p>
        </div>
        
        <p><a href="{% url 'usuarios:password_reset' %}">Esqueceu sua senha?</a></p>
        
    </div>

</body>

</html>

templates/usuarios/password_change_done.html
{% extends 'polls/base.html' %}


{% block content %}
<h1>Alteração de senha</h1>
<p>Sua senha foi alterada com sucesso</p>
{% endblock %}

templates/usuarios/password_change_form.html
{% extends 'polls/base.html' %}

<title>Altere sua senha</title>
{% block content %}

<h1>altere sua senha</h1>
<p>use o formulario abaixo para alterar sua senha</p>

<form method="post">
{{ form.as_p }}

<p><input type="submit" value="Alterar"></p>
    {% crsf_token %}
</form>


{% endblock %}

templates/usuarios/password_reset_complete.html
{% extends 'polls/base.html' %}
<h1>Redefinir sua senha </h1>
{% block title %} 
    <h1> Redefinir sua senha </h1>
    <p>Sua senha foi redefinida com sucesso. Você pode 
        <a href="{% url 'usuarios:login' %}">Conectar-se agora</a></p>

{% endblock %} 

templates/usuarios/password_reset_confirm.html
{% extends 'polls/base.html' %}
<h1>Redefinir senha</h1>
{% block content %}
    <h1>Redefinir senha</h1>
    {% if validlink %}
    <p>Por favor, digite sua nova senha duas vezes:</p>
    <form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Alternar minha senha"></p>
    </form>
    {% else %}
    <p>O link de redefinição de senha era inválido, possivelmente ja foi utilizad. Solicite uma nova redefinição de senha</p>
    {% endif %}
{% endblock %}

templates/usuarios/password_reset_done.html
{% extends 'polls/base.html' %}
<h1>Redefinir sua senha </h1>
{% block title %} 
    <h1> Redefinir sua senha </h1>
    <p>Enviamos a você por email, intruções para definir sua nova senha</p>
    <p>Se você nao receber um e-mail, verifique se digitou o endereço de e-mail corretamente</p>

{% endblock %} 

templates/usuarios/password_reset_email.html
Você solicitou a redefinição de senha do e-mail {{ email }}.
Segue o link abaixo:
{{ protocol }}://{{ domain }}{% url 'usuarios:password_reset_confirm' uidb64=uid token=token %}

Seu nome de usuário, caso você tenha esquecido: {{ user.get_username }}

templates/usuarios/password_reset_form.html
{% extends 'polls/base.html' %}

<title>Resete sua senha</title>
{% block coontent %}
<h1>Esqueceu sua senha?</h1>
    <p>entre com seu email para resetar sua senha</p>

<form method="post">
    {{ form.as_p }}

    <p><input type="submit" value="Enviar email"></p>
    {% crsf_token %}


</form>
{% endblock %}